### ISSUE TITLE
Application Form Navigation

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/digital-platform#90]
We want the application the application form to be displayed in this order:

- [x] Register / login (requires JudicialAppointmentsCommission/digital-platform#22)
- [x] Introduction (requires JudicialAppointmentsCommission/digital-platform#107)
- [x] Your nationality (requires JudicialAppointmentsCommission/digital-platform#30)
- [x] Your personal details (requires JudicialAppointmentsCommission/digital-platform#42)
- [x] Your qualifications (requires JudicialAppointmentsCommission/digital-platform#76)
- [x] Your experience (requires JudicialAppointmentsCommission/digital-platform#101)
- [x] Your self-assessment (requires JudicialAppointmentsCommission/digital-platform#97)
- [x] Your assessors (requires JudicialAppointmentsCommission/digital-platform#94)
- [x] Your character (including professional body checks) (requires JudicialAppointmentsCommission/digital-platform#91)
- [x] Your preferences (requires JudicialAppointmentsCommission/digital-platform#93)
- [x] Declarations (requires JudicialAppointmentsCommission/digital-platform#98)
- [x] Diversity (requires JudicialAppointmentsCommission/digital-platform#45)
- [x] Media questions JudicialAppointmentsCommission/digital-platform#106)
- [x] Review and submit your application (requires JudicialAppointmentsCommission/digital-platform#59)

**Comment by ClaireTroughtonJAC** [comment]
We would like the application form navigation to follow this order: 

1 . Nationality
2. Personal Details
3.Career History
4.Exercise specific answers
5. Character
6. Declarations (incorporating the confidentiality statement)
7. Diversity
8.  Media survey/feedback

**Comment by LaurieJohnston** [comment]
This order makes sense to me so far - can we discuss

Register / login
Your nationality
Your personal details
Your qualifications (including legal)
Your judicial appointments
Your career history
Your other legal experience
Your personal statement
Your character (including professional body checks)
Your assessors 
Declaration
Diversity 
Review and submit your application
Invitation to give feedback on form or take part in user research
